"""
Chop regime C1 -- REPORT.md, generated from the artifacts (every number is read by code). Describes; interprets nothing.

This version is the record of the T5 HARD STOP (escalation row 3): T0 and T5 ran, T6-T9 did not. It writes
results/chop_regime/c1/REPORT.md and its copy results/reports/chop_regime_c1_report.md.

Usage: .venv/Scripts/python.exe research/chop_regime_c1/c1report.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import c1common as C  # noqa: E402


def f(x, d=3):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "—" if x is None or np.isnan(x) else ("inf" if x > 0 else "-inf")
    if isinstance(x, (int, np.integer)):
        return f"{int(x):,}"
    ax = abs(x)
    if ax != 0 and (ax >= 1e6 or ax < 1e-3):
        return f"{x:.3g}"
    return f"{x:,.{d}f}"


def main() -> int:
    cfg = C.load_cfg()
    t0 = C.read_json("t0_summary.json")
    t5 = C.read_json("t5_summary.json")
    t5a = C.read_json("t5a_summary.json")
    P = pd.read_parquet(C.art("t5_pooled.parquet"))
    W = pd.read_parquet(C.art("t5_windows.parquet"))
    BL = pd.read_parquet(C.art("t5_blindness.parquet"))
    BD = pd.read_parquet(C.art("t5b_blindness_detail.parquet"))
    AG = pd.read_parquet(C.art("t5_basis_agreement.parquet"))
    D = pd.read_parquet(C.art("t5a_whole_pipeline_diagnosis.parquet"))
    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=C.REPO).stdout.strip()
    freeze = subprocess.run(["git", "log", "--format=%h", "-1", "--grep=T0 freeze"], capture_output=True, text=True, cwd=C.REPO).stdout.strip()
    pop, tim, cen = t0["population"], t0["timing"], t0["quote_size_census"]
    tb = t5["table"]
    L = []
    a = L.append
    a("# Chop regime filter — C1: the measures and the tuning suite")
    a("")
    a(f"**Generated by** `research/chop_regime_c1/c1report.py` from `results/chop_regime/c1/artifacts/` at `HEAD {head}`; every number below is read from an artifact. "
      f"**Config** `config/chop_regime_c1.json`, hash `{C.cfg_hash()}`. **Brief** `prompts/chop_regime_c1.md`. **Branch** `explore/chop-regime-c1` "
      f"(cut from `explore/shape-classifier-s2` at `e71b68a`).")
    a("")
    a("**Status: HARD STOP at T5 — escalation row 3 fires.** Both bucket prices fail the whole-pipeline control, so the ruling table's "
      "\"fails / fails\" cell applies. The other gated failures are listed below. State is committed. Nothing is fixed or tuned. T6–T9 did not run: "
      "there is no full build, no gallery and no suite.")
    a("")
    # ------------------------------------------------------------ escalation
    a("## Escalation table")
    a("")
    a("| row | criterion | tier | status | observed |")
    a("|---|---|---|---|---|")
    caus, seg = t5["tests"]["causality"], t5["tests"]["segment"]
    a(f"| 1 | any causality assertion fires | HARD STOP | clear | the causality test raises in all {sum(v == 'raised' for v in caus.values())} cases; no assertion fired in the T0 timing builds or the T5 builds of the 53 events |")
    a(f"| 2 | any segment assertion fires | HARD STOP | clear | the segment test raises in all {sum(v == 'raised' for v in seg.values())} cases; no assertion fired in any build |")
    failing = [k for k, v in tb.items() if isinstance(v, dict) and v.get("pass") is False] + [k for k, v in t5["gated"].items() if not v]
    a(f"| 3 | any §6 control misses its pass band | HARD STOP | **FIRES** | the whole pipeline fails on the midpoint and on VWAP (ruling `{t5['ruling']['case']}`, no basis kept); "
      f"failing: {', '.join(f'`{x}`' for x in failing)} |")
    a(f"| 4 | quote-size units cannot be established for a year | LOG | clear | shares in {', '.join(y for y, v in cen.items() if v['unit'] == 'shares')} |")
    a("| 5 | embedded sample below 50% of development-slice events | LOG | not reached | T8 did not run |")
    a("| 6 | moments with no valid scale-free rung above 40% of moment-minutes in any segment | LOG | not reached | T6 did not run |")
    a(f"| 7 | events with quotes unavailable | LOG | **fires** | {pop['development_quotes_ingested_false']} development-slice events have `quotes_ingested = FALSE` (D15 source); "
      f"{pop['development_quotes_event_day_false']} have no event-day quote session |")
    a("| 8 | A12 or a hindsight column reaches the suite's condition inputs | HARD STOP | not reached | T8 did not run |")
    a("| 9 | any embedded row outside the development slice | HARD STOP | not reached | T8 did not run |")
    a(f"| 10 | extrapolated runtime above 6 hours | HARD STOP | clear | {f(tim['extrapolated_wall_hours'], 2)} h on {tim['workers']} workers ({f(tim['serial_hours'], 2)} h serial) |")
    a("")
    a(f"**D40 and D41.** Both were appended to `docs/Universe-Decisions.md`, with the `CLAUDE.md` index (next free D42), in the T0 freeze commit `{freeze}`, "
      "before any run. D40 is verbatim from the brief. D41 records Cooper's ruling at T0: C1's suite may put turnover (whose denominator is F1's share count) and the dilution flag "
      "beside outcome panels as an exploratory, by-eye exception to D32, in the same shape as D39. `tools/verify_claude_md_indices.py` reported all indices clean.")
    a("")
    # ------------------------------------------------------------ T0
    a("## T0 — population, τ, quote sizes, tests, timing")
    a("")
    a(f"- **τ source:** {t0['tau_source']}.")
    a(f"- **Development slice:** {f(pop['slices_development'])} events in `slices.parquet`; {f(pop['development_with_tau'])} with τ "
      f"(b2 `tau_available`: {f(pop['b2_development_tau_available'])}). Without τ: {', '.join(f'{k} {v}' for k, v in pop['development_without_tau'].items())}.")
    a(f"- **Quarantine:** {pop['slices_quarantine']} events; **{pop['quarantine_with_tau']} with τ** "
      f"({', '.join(f'{k} {v}' for k, v in pop['quarantine_by_group'].items())}). Moments are defined from τ, so the §6 controls run on "
      f"{pop['quarantine_with_tau']}. Without τ: {', '.join(x['event_id'] + ' (' + x['tau_reason'] + ')' for x in pop['quarantine_without_tau'])}.")
    a(f"- **By year (with τ):** {', '.join(f'{k} {f(v)}' for k, v in pop['development_by_year'].items())}. **τ's segment:** "
      f"{', '.join(f'{k} {f(v)}' for k, v in pop['development_by_tau_segment'].items())}.")
    a(f"- **Carried gaps:** `V_pre` undefined (τ in an auction minute) for {pop['development_v_pre_undefined']}; S2's τ-anchored share count missing for "
      f"{f(pop['development_shares_outstanding_missing'])} (turnover unavailable there); τ_d later than the stored τ for {f(pop['tau_after_stored'])} "
      "(the 256 ns float64 rounding S2 recorded).")
    a("")
    a("**Quote-size unit census** (config rule: shares if ≥ 95% of D17-valid sizes are multiples of 100 and the median at-touch trade / displayed size is ≤ 1; "
      "lots if ≤ 5% and ≥ 10):")
    a("")
    a("| year | events | events with quotes | sizes | share multiple of 100 | median of event medians | at-touch trades | median trade / displayed | share trade ≤ displayed | unit |")
    a("|---|---|---|---|---|---|---|---|---|---|")
    for y, v in cen.items():
        a(f"| {y} | {v['events']} | {v['events_with_quotes']} | {f(v['sizes'])} | {f(v['share_multiple_of_100'], 4)} | {f(v['size_median_of_event_medians'], 0)} | "
          f"{f(v['at_touch_trades'])} | {f(v['median_trade_over_displayed'])} | {f(v['share_trade_le_displayed'])} | **{v['unit']}** |")
    a("")
    tt = t0["tests"]
    a(f"**Tests.** Causality: {tt['causality']['passes']}. Segment: {tt['segment']['passes']}. Bucket construction against Brief 1's `instruments.bucketize` on "
      f"{tt['bucket_equality']['windows']} random tapes: max relative VWAP difference {f(tt['bucket_equality']['max_rel_vwap_diff'])}, bucket end time difference "
      f"{tt['bucket_equality']['max_t_end_diff_ns']} ns.")
    a("")
    a(f"**Timing** (`t0_timing.parquet`): {tim['events_timed']} quarantined events, {f(tim['seconds_total'], 1)} s in total (median {f(tim['seconds_median'], 2)} s, "
      f"max {f(tim['seconds_max'], 2)} s). Wall ≈ {f(tim['fit']['a_s'], 3)} s + {tim['fit']['b_s_per_print']:.3g} s per print; over the development slice's "
      f"{f(tim['dev_prints_total'], 0)} prints: {f(tim['serial_hours'], 2)} h serial, {f(tim['extrapolated_wall_hours'], 2)} h on {tim['workers']} workers. "
      "T0's timing was measured before the VWAP-deviation change recorded under T5. That change adds one cumulative sum per window.")
    a("")
    # ------------------------------------------------------------ T5
    a("## T5 — the §6 controls (53 quarantined events)")
    a("")
    wb = t5["windows_by_basis"]
    a(f"Windows: {', '.join(f'{k} {f(v)}' for k, v in wb.items())} (every valid scale-free window of every non-auction moment; rungs "
      f"{min(int(k) for k in t5['windows_by_rung'])}–{max(int(k) for k in t5['windows_by_rung'])}). Charts: `charts/t5/`.")
    a("")
    a("### Control table")
    a("")
    a("| control | basis | statistic (pooled over rungs) | band | observed | pass | failing rungs |")
    a("|---|---|---|---|---|---|---|")
    nr = cfg["controls"]["negative_references"]
    for ctl, lab in (("references", "negative — the references"), ("whole_pipeline", "negative — the whole pipeline (literal shuffle)")):
        for bs in C.BASES:
            x = tb[f"{ctl}|{bs}"]
            al = x["all_rungs"]
            fr = ", ".join(x["failing_rungs"]) if x["failing_rungs"] else "none"
            a(f"| {lab} | {bs} | median over windows of the ER statistic (n windows {f(al['windows'])}) | {nr['er_ratio_band'][0]}–{nr['er_ratio_band'][1]} | "
              f"{f(al['er_statistic_median'])} | {'yes' if al['pass_er'] else '**no**'} | |")
            a(f"| | | vz2 median / SD (n draws {f(al['vz2_n'])}) | \\|median\\| < {nr['vz_abs_median_max']}; SD {nr['vz_sd_band'][0]}–{nr['vz_sd_band'][1]} | "
              f"{f(al['vz2_median'])} / {f(al['vz2_sd'])} | | |")
            a(f"| | | vz4 median / SD (n draws {f(al['vz4_n'])}) | same | {f(al['vz4_median'])} / {f(al['vz4_sd'])} | {'yes' if al['pass_vz'] else '**no**'} | "
              f"{'**' + fr + '**' if x['failing_rungs'] else fr} (gate: every rung) |")
    for bs in C.BASES:
        x = tb[f"positive_trend|{bs}"]
        a(f"| positive — trend | {bs} | median er_rel at d = 1, 2, 4 | rises with d; > 2.0 at d = 4 | "
          f"{', '.join(f(v) for v in x['median_er_rel_by_d'].values())} | {'yes' if x['pass'] else '**no**'} | |")
    for bs in C.BASES:
        x = tb[f"positive_autocorrelation|{bs}"]
        a(f"| positive — autocorrelation | {bs} | median vz2 at φ = +0.5 / −0.5 | ≥ +1.64 / ≤ −1.64 | {f(x['median_vz2_by_phi']['+0.50'])} / "
          f"{f(x['median_vz2_by_phi']['-0.50'])} | {'yes' if x['pass'] else '**no**'} | |")
    for bs in C.BASES:
        x = tb[f"edge_of_detectability|{bs}"]
        a(f"| edge of detectability | {bs} | median vz2 at φ = ±0.25; median er_rel at d = 1 | report only | {f(x['median_vz2_phi_+0.25'])} / "
          f"{f(x['median_vz2_phi_-0.25'])}; {f(x['median_er_rel_d1'])} | — | |")
    bl = t5["blindness"]
    a(f"| blindness | both | trade and quote prices × 10 and × 0.1, every invariant column and every scale-free rung | `isclose(rtol = atol = 1e-9)`, NaN / inf patterns equal | "
      f"{bl['values_not_close']} values not close; **{bl['nan_pattern_mismatches']} NaN / inf pattern mismatches** | {'yes' if bl['passes'] else '**no**'} | |")
    a(f"| causality | — | measures fed a print and a quote 1 ns after t | must raise | raised in every case | {'yes' if t5['gated']['causality'] else '**no**'} | |")
    a(f"| segment | — | windows crossing a boundary or holding an auction minute | must raise | raised in every case | {'yes' if t5['gated']['segment'] else '**no**'} | |")
    a("")
    r = t5["ruling"]
    a(f"**Primary-price ruling (§6 table):** midpoint passes the whole pipeline: {r['whole_pipeline_mid_pass']}; VWAP passes: {r['whole_pipeline_vwap_pass']} → "
      f"case `{r['case']}` → **HARD STOP (row 3)**. Charts: `charts/t5/01_null_er_by_rung.html` (ER statistic per rung), "
      "`charts/t5/02_null_vz_by_rung.html` (z median and SD per rung), `charts/t5/05_positive_controls.html`.")
    a("")
    # sweep
    a("### Null-parameter sweep (buckets 16 / 32 / 64; a label, not a gate)")
    a("")
    a("| basis | measure | median at 16 | at 32 | at 64 | relative change 16 / 64 | bucket-dependent (> 20%) |")
    a("|---|---|---|---|---|---|---|")
    for bs in C.BASES:
        sw = tb[f"null_parameter_sweep|{bs}"]
        for m in ["er_rel", "vz2"] + [f"cost_noise_{h}" for h in C.HORIZONS]:
            x = sw[m]
            a(f"| {bs} | {m} | {f(x['16'])} | {f(x['32'])} | {f(x['64'])} | {f(x['rel_change_16'])} / {f(x['rel_change_64'])} | {'**yes**' if x['bucket_dependent'] else 'no'} |")
    a("")
    a("Real windows (not a null); `cost_noise_h` is read at each moment's finest valid rung. A median near zero makes a relative change large: vz2's absolute changes are "
      + "; ".join(f"{bs} {f(tb[f'null_parameter_sweep|{bs}']['vz2']['abs_change_16'])} / {f(tb[f'null_parameter_sweep|{bs}']['vz2']['abs_change_64'])}" for bs in C.BASES) + ".")
    a("")
    # blindness
    a("### Blindness")
    a("")
    a(f"Rule (config, set before the T5 run): {bl['rule']}")
    a("")
    bad = BL[(BL["x10_nan_pattern_mismatches"] > 0) | (BL["x0.1_nan_pattern_mismatches"] > 0)]
    a(f"Values not close under either rescaling: {bl['values_not_close']}. Relative-only worst case: × 10 {f(bl['x10_max_rel_diff_relative_only'])}, "
      f"× 0.1 {f(bl['x0.1_max_rel_diff_relative_only'])}. NaN / inf pattern mismatches: {bl['nan_pattern_mismatches']}, in {len(bad)} events "
      f"({', '.join(f'{e} (×10: {a_}, ×0.1: {b_})' for e, a_, b_ in zip(bad['event_id'], bad['x10_nan_pattern_mismatches'], bad['x0.1_nan_pattern_mismatches']))}). "
      f"Those events' share of sub-$1 prints: {', '.join(f(x) for x in bad['sub_dollar_share'])}. Sub-$1 rounding to the $0.01 grid ({bl['events_with_sub_dollar_prints']} events "
      "with sub-$1 prints) is reported per event in `t5_blindness.parquet`.")
    a("")
    # agreement
    a("### Price-basis agreement (Spearman, midpoint vs VWAP, real windows)")
    a("")
    g = AG.groupby(["measure", "segment"]).apply(lambda x: pd.Series({"rungs": len(x), "n": int(x["n"].sum()),
                                                                      "spearman_median_over_rungs": float(x["spearman"].median()),
                                                                      "min": float(x["spearman"].min()), "max": float(x["spearman"].max())}), include_groups=False).reset_index()
    a("| measure | segment | rungs | n windows | median over rungs | min | max |")
    a("|---|---|---|---|---|---|---|")
    for x in g.itertuples():
        a(f"| {x.measure} | {x.segment} | {x.rungs} | {f(int(x.n))} | {f(x.spearman_median_over_rungs)} | {f(x.min)} | {f(x.max)} |")
    a("")
    a("Per rung and segment: `t5_basis_agreement.parquet`.")
    a("")
    # ------------------------------------------------------------ recorded at the stop
    a("## Recorded at the stop, not fixed")
    a("")
    a("**1. The whole-pipeline null as written is a bridge.** A permutation keeps the sum of the returns, so every shuffled path begins and ends where the real "
      "window does and carries the window's own net move. `t5a_whole_pipeline_diagnosis.py` measures three constructions on the same windows "
      "(20 draws each) against the reference bands (`charts/t5/04_whole_pipeline_constructions.html`):")
    a("")
    a("| construction | basis | n windows | ER statistic | vz2 median | vz2 SD | vz4 median | vz4 SD | passes every rung |")
    a("|---|---|---|---|---|---|---|---|---|")
    for x in D[D["rung"] == "all"].itertuples():
        a(f"| {x.kind} | {x.basis} | {f(x.windows)} | {f(x.er_statistic_median)} | {f(x.vz2_median)} | {f(x.vz2_sd)} | {f(x.vz4_median)} | {f(x.vz4_sd)} | "
          f"{t5a['passes_every_rung'][f'{x.kind}|{x.basis}']} |")
    a("")
    a("No construction passes on either basis. On VWAP the vz2 median sits at about +1.45 under all three. On the midpoint the z SD is in the 1e10 range or above, "
      "and the vz4 median is below −0.15, under all three.")
    a("")
    wq = W.groupby("basis")["vz2"].agg(lambda s: (s.abs() > 10).mean())
    wq100 = W.groupby("basis")["vz2"].agg(lambda s: (s.abs() > 100).mean())
    a("**2. The robust z's variance term reaches zero on sparse returns.** z* = √n (VR − 1) / √θ, with θ built from δ_j = n Σ d_t² d_{t−j}² / (Σ d_t²)². "
      "When the non-zero bucket returns are isolated and their mean is about 0, every lagged product is about 0, so θ approaches 0 and z grows without bound. On the real windows, "
      f"|vz2| > 10 in {', '.join(f'{b} {f(100 * wq[b], 2)}%' for b in C.BASES)} of windows, and > 100 in "
      f"{', '.join(f'{b} {f(100 * wq100[b], 2)}%' for b in C.BASES)} (`charts/t5/03_real_vz2_tails.html`). The pooled null SDs in the control table are driven by such windows. "
      "The resampling null keeps a window's sparsity, so the reference control fails its SD band on the midpoint at every rung, and on VWAP at rungs "
      f"{', '.join(tb['references|vwap']['failing_rungs'])}.")
    a("")
    bdm = BD[BD["level"] == "moment"]
    a("**3. The blindness mismatches are the same degenerate z.** `t5b_blindness_detail.py` rebuilds the events concerned. Every NaN / inf mismatch is "
      f"`{'`, `'.join(sorted(BD['column'].unique()))}`, finite at one scale and infinite at the other: "
      + "; ".join(f"{x.event_id} j = {x.j} at x{x.factor:g}: {f(x.value_x1)} (x1) vs {f(x.value_rescaled)}" for x in bdm.itertuples())
      + f". Each is counted on the moment row and on its rung row ({len(BD)} in all). The rule's atol absorbs the midpoint rounding that motivated it "
      "((0.1 bid + 0.1 ask) / 2 is not bit-equal to 0.1 (bid + ask) / 2; er 0 vs about 1e-15 on a flat midpoint path), and no value fails isclose.")
    a("")
    a("**4. A change made before the T5 run, recorded.** VWAP buckets are computed on each print's deviation from the window's first print (`measures.vwap_log_path`). "
      "A constant-price bucket is then exact, and two such buckets give an exact zero return. On raw dollar prefix sums a flat stretch returned rounding noise (~1e-12), which is "
      "not scale-invariant. The bucket edges, owners and value split are Brief 1's rule (`buckets_core`, tested against `instruments.bucketize`). Dollar conservation is asserted in "
      "every window.")
    a("")
    # ------------------------------------------------------------ not run
    a("## Not run")
    a("")
    a("T6 (full build on the development slice), T7 (gallery pools), T8 (the suite) and T9's suite-dependent reporting: no per-moment measure exists for the development slice, "
      "no distribution per segment, no column dictionary, no embedded sample fraction. No development-slice outcome was computed or read. The hindsight columns "
      "were computed only in T0's timing builds of the quarantined events, and no artifact holds them. During a smoke test of the builder, one quarantined event's forward "
      "15-minute return (MATX_2020-07-10, eight moments) was printed to the console.")
    a("")
    a("## Files")
    a("")
    a("- Code: `research/chop_regime_c1/` — `c1common.py`, `measures.py`, `t0_population.py`, `t5_controls.py`, `t5a_whole_pipeline_diagnosis.py`, `t5b_blindness_detail.py`, `c1charts.py`, `c1report.py`.")
    a("- Artifacts: `results/chop_regime/c1/artifacts/` — `t0_population.parquet`, `t0_census.parquet`, `t0_timing.parquet`, `t0_summary.json`, `t5_windows.parquet`, "
      "`t5_pooled.parquet`, `t5_blindness.parquet`, `t5_basis_agreement.parquet`, `t5_summary.json`, `t5a_whole_pipeline_diagnosis.parquet`, `t5a_summary.json`, "
      "`t5b_blindness_detail.parquet`.")
    a("- Charts: `results/chop_regime/c1/charts/t5/` — `01_null_er_by_rung.html`, `02_null_vz_by_rung.html`, `03_real_vz2_tails.html`, "
      "`04_whole_pipeline_constructions.html`, `05_positive_controls.html` (one offline `plotly.min.js` beside them). Two categorical colour slots are used (blue / orange). "
      "Deviation from the chart contract: the null z-draws were not retained, so `02` shows their spread as an SD.")
    out = C.REPO / C.OUT / "REPORT.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    cp = C.REPO / "results" / "reports" / "chop_regime_c1_report.md"
    shutil.copyfile(out, cp)
    print(out, cp)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
