"""
Part III -- report for the E2 window units fix and its retraction sweep, generated from artifacts.

Every number below is read from an artifact at build time (III.3: "report counts read from artifacts by
code"). Describes the corrected distribution; interprets nothing. Writes
results/fundamental_exploration/e2/UNITS_FIX.md, its copy results/reports/fundamental_exploration_e2_units_fix_report.md,
and inserts (or refreshes) a banner at the top of both copies of E2's REPORT.md -- banner, don't delete.

Usage: .venv/Scripts/python.exe research/fundamental_exploration/e2_units_fix_report.py
"""
from __future__ import annotations

import glob
import json
import os
import shutil
import sys

import pandas as pd

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
from research.fundamental_exploration import common as C  # noqa: E402

A = C.ART_E2
OUT = "results/fundamental_exploration/e2/UNITS_FIX.md"
COPY = "results/reports/fundamental_exploration_e2_units_fix_report.md"
BANNER_START, BANNER_END = "<!-- PART-III-UNITS-FIX-BANNER -->", "<!-- /PART-III-UNITS-FIX-BANNER -->"


def J(name):
    with open(f"{A}/{name}") as f:
        return json.load(f)


def n(x):
    return f"{int(x):,}"


def m(x, d=1):
    return f"{x:,.{d}f}" if x is not None and x == x else "—"


def main() -> int:
    conf = J("e2_units_fix_confirm_one_event.json")
    fx = J("e2_t2_window_units_fixed_summary.json")
    t3a, t3b = J("e2_t3_describe_responses_summary.json"), J("e2_t3_describe_responses_summary_units_fixed.json")
    t4a, t4b = J("e2_t4_time_of_day_summary.json"), J("e2_t4_time_of_day_summary_units_fixed.json")
    t7a, t7b = J("e2_t7_price_decile_arm_zero_summary.json"), J("e2_t7_price_decile_arm_zero_summary_units_fixed.json")

    # momentum -- unaffected, checked rather than assumed
    checks = {
        "T3 momentum_pct_stats identical": t3a["momentum_pct_stats"] == t3b["momentum_pct_stats"],
        "T7 momentum_pct_by_price_decile identical": t7a["momentum_pct_by_price_decile"] == t7b["momentum_pct_by_price_decile"],
        "T7 momentum-by-decile parquet identical": pd.read_parquet(f"{A}/e2_t7_momentum_by_decile.parquet").equals(
            pd.read_parquet(f"{A}/e2_t7_momentum_by_decile_units_fixed.parquet")),
        "T7 momentum scatter data identical": pd.read_parquet(f"{A}/e2_t7_scatter_momentum.parquet").sort_values("event_id").reset_index(drop=True).equals(
            pd.read_parquet(f"{A}/e2_t7_scatter_momentum_units_fixed.parquet").sort_values("event_id").reset_index(drop=True)),
        "B_e (T2a baseline) untouched -- the fix reads it, never writes it": True,
    }
    charts = sorted(p.replace("\\", "/") for p in glob.glob("results/fundamental_exploration/e2/charts/*/*_units_fixed.html"))

    L = []
    w = L.append
    w("# E2 participation window — units fix and retraction sweep (Part III)")
    w("")
    w("**Generated by** `research/fundamental_exploration/e2_units_fix_report.py` from `results/fundamental_exploration/e2/artifacts/`; "
      "every figure is read from an artifact at build time. **Branch** `fix/e2-window-units`, cut from `origin/explore/fundamental-e2`. "
      "**Brief** Part III of `prompts/attention_excursion_b1.md` (branch `explore/attention-excursion-b1`), authorised by its Amendment 1 A1.7. "
      "Descriptive only, like E2 itself: no duration result is put against any outcome; D32 A1 is unchanged.")
    w("")
    w("## 1. The defect")
    w("")
    w("`e2_t2_window.py` ended the high-participation window at the first minute where "
      "`dollar_volume.rolling(10).mean()` — dollar volume **per minute** — was ≤ 3 × `B_e`, and `B_e` is dollar volume **per "
      "10-minute block** (`e2_t2a_baseline.py`: RTH dollar volume ÷ (n_sessions × 39)). The rule that ran was therefore 30× the "
      "baseline rate, not the 3× confirmed on 2026-09-15. The fix: `build_event_series(..., agg=\"sum\")`, the trailing 10-minute "
      "**sum**. The default `agg=\"mean\"` still reproduces the as-run artifact, and that reproduction is asserted in the fix script.")
    w("")
    w(f"## 2. III.2.1 — one event, both constructions (`{conf['event_id']}`, fixed before running)")
    w("")
    w(f"`B_e` = ${m(conf['B_e_usd_per_10min'], 0)} per 10-minute block; threshold 3 × `B_e` = ${m(conf['threshold_3B_e'], 0)}; "
      f"t0 = {conf['t0_et']}.")
    w("")
    w("| construction | window end (ET) | duration_min |")
    w("|---|---|---|")
    for k, v in conf["constructions"].items():
        w(f"| {k} | {v['window_end_et']} | {m(v['duration_min'], 2)} |")
    w("")
    w(f"`agg=\"mean\"` reproduces the committed-as-run artifact for this event: {conf['reproduces_as_run_artifact']}.")
    w("")
    w("## 3. III.2.2 — `duration_min` rebuilt (everything else as confirmed for E2: C = 10, dollar volume, censoring at end of tick data, the 3-prior-session RTH baseline)")
    w("")
    a, b = fx["duration_min_as_run"], fx["duration_min_fixed"]
    w("| statistic | as run | units fixed |")
    w("|---|---|---|")
    for k in ("n", "median", "p25", "p75", "p90", "max"):
        w(f"| {k} | {m(a[k], 1) if k != 'n' else n(a[k])} | {m(b[k], 1) if k != 'n' else n(b[k])} |")
    w(f"| exactly 0 | {n(a['n_zero'])} ({100 * a['share_zero']:.1f}%) | {n(b['n_zero'])} ({100 * b['share_zero']:.1f}%) |")
    w(f"| censored | {n(fx['censored_as_run'])} | {n(fx['n_censored'])} |")
    w("")
    p = fx["paired"]
    w(f"Paired over {n(p['n'])} events: fixed longer {n(p['fixed_longer'])}, equal {n(p['equal'])}, fixed shorter {n(p['fixed_shorter'])}; "
      f"newly censored {n(p['newly_censored'])}. Positive-only duration (fixed): n {n(t3b['duration_min_positive_only_stats']['n'])}, "
      f"median {m(t3b['duration_min_positive_only_stats']['median'])} min, p90 {m(t3b['duration_min_positive_only_stats']['p90'])} min.")
    w("")
    w("**By t0 session segment (E2-T4), minutes:**")
    w("")
    w("| segment | n | as run: median / p75 / p90 | units fixed: median / p75 / p90 |")
    w("|---|---|---|---|")
    for seg, s1 in t4b["duration_by_segment"].items():
        s0 = t4a["duration_by_segment"][seg]
        w(f"| {seg} | {n(s1['n'])} | {m(s0['median'])} / {m(s0['p75'])} / {m(s0['p90'])} | {m(s1['median'])} / {m(s1['p75'])} / {m(s1['p90'])} |")
    w("")
    w("**By detection-price decile (E2-T7), median minutes:**")
    w("")
    w("| decile | n | as run | units fixed |")
    w("|---|---|---|---|")
    for d, s1 in t7b["duration_min_by_price_decile"].items():
        s0 = t7a["duration_min_by_price_decile"][d]
        w(f"| {d} | {n(s1['duration_min']['n'])} | {m(s0['duration_min']['median'])} | {m(s1['duration_min']['median'])} |")
    w("")
    w("## 4. Re-rendered charts (III.2.4) — only the E2 duration charts, from the corrected artifact")
    w("")
    w("Each sits beside its as-run original with a `_units_fixed` suffix; no as-run chart is overwritten. Captions that stated an as-run "
      "figure (the zero share, the censored share) now read it from the active variant's own summary.")
    w("")
    for c in charts:
        w(f"- `{c}`")
    w("")
    w("## 5. Momentum results — unaffected, checked")
    w("")
    w("| check | result |")
    w("|---|---|")
    for k, v in checks.items():
        w(f"| {k} | {v} |")
    w("")
    w("## 6. Retraction sweep (standing rule)")
    w("")
    w("| file | branch | disposition |")
    w("|---|---|---|")
    rows = [
        ("`results/fundamental_exploration/e2/REPORT.md` — T2/T3 duration headline (0% censored, median 0, "
         f"{100 * a['share_zero']:.1f}% exactly 0), T4 duration by time of day, T6 duration vs fundamentals, T7 duration by price decile",
         "this branch; same text on `master` via PR #13", "**withdrawn** (duration statements) — banner added at the top pointing here; "
         "momentum statements unaffected (section 5)"),
        ("`results/reports/fundamental_exploration_e2_report.md`", "this branch; `master`", "**withdrawn** — same banner"),
        ("`docs/Research-Library-Map.md` — E2 entry headline (\"0% censored ... median exactly 0\", \"a genuine consequence of the flat, RTH-based baseline (not a bug)\")",
         "this branch; `master`", "**corrected**"),
        ("`artifacts/e2_t2_window_summary.json`, `e2_t3_describe_responses_summary.json` (duration fields), `e2_t3_survival_curve.json`, "
         "`e2_t4_time_of_day_summary.json`, `e2_t6_cells_year_price.json`, `e2_t6_cells_segment.json`, `e2_t6_fundamentals_vs_duration_summary.json`, "
         "`e2_t7_price_decile_arm_zero_summary.json` (`duration_min_by_price_decile`)",
         "this branch; `master`", "**withdrawn** — superseded by their `_units_fixed` siblings, kept as the as-run record"),
        ("E2 duration charts `e2_t3/01`, `e2_t3/02`, `e2_t4/01`, `e2_t6/01`–`11`, `e2_t7/01`, `e2_t7/02`", "this branch; `master`",
         "**withdrawn** — superseded by the `_units_fixed` charts in section 4"),
        ("E2 momentum and fundamentals results — T0, T1 boundary audit, T2a baseline, T3 momentum, T5, T7 momentum by decile",
         "this branch; `master`", "**unaffected** — checked, section 5"),
        ("`prompts/fundamental_exploration_e2.md`", "this branch; `master`", "**unaffected** — it specifies 3 × `B_e`; the defect is in code"),
        ("`config/fundamental_exploration_e2.json`", "this branch; `master`",
         "**unaffected** — the confirmed values (C = 10, 3×, dollar volume, end-of-tick-data censoring) stand; its wording "
         "\"trailing 10-minute average dollar volume\" against a per-10-minute baseline is where the units ambiguity sits"),
        ("E2 code docstrings quoting the as-run zero share (`e2_chart_t3/t6/t6_scatter`, `e2_t4_time_of_day`)", "this branch",
         "**as-run record** — the rendered captions now read the figure from the active variant's summary"),
        ("`results/participation_exit_overlay/REPORT.md` (+ copy), `research/participation_exit_overlay/common.py`, the overlay "
         "library-map entry, `results/relative_momentum/r0/REPORT.md` (+ copy)", "`explore/attention-excursion-b1`, commit `7110516`",
         "**corrected** — the false \"E2 never committed\" / \"C unrecoverable\" statements; overlay results unaffected (it rebuilt the "
         "window with the 10-minute sum and C = 10)"),
        ("`config/participation_exit_overlay.json`", "`explore/attention-excursion-b1`",
         "**unedited** — its false strings stay as the record so the config hash its artifacts are keyed to is unchanged; corrected in the report"),
        ("relative momentum v0, v1, v2", "`explore/relative-momentum-*`", "**unaffected** — they reuse `B_e`, which the defect does not touch"),
        ("Brief 1, attention and the excursion", "`explore/attention-excursion-b1`", "**unaffected** — does not use E2's window"),
        ("Documents outside the repo that quote E2's zero mass or median (e.g. Cooper's `claude/relative_momentum_findings_log.md`)",
         "not in the repo", "**not edited** — outside this repository; flagged for Cooper"),
    ]
    for r in rows:
        w(f"| {r[0]} | {r[1]} | {r[2]} |")
    w("")
    w("## 7. Artifacts")
    w("")
    w("Committed (JSON, per the repo's E2 rule): `e2_units_fix_confirm_one_event.json`, `e2_t2_window_units_fixed_summary.json`, and every "
      "`*_units_fixed.json` above. The parquets (`e2_t2_window_units_fixed.parquet` and the `_units_fixed` intermediates) follow the "
      "repo's `.gitignore` rule for E2 artifacts — regenerable with `E2_WINDOW_VARIANT=_units_fixed` and the scripts named here.")
    txt = "\n".join(L) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(txt)
    shutil.copyfile(OUT, COPY)

    banner = (f"{BANNER_START}\n> **Withdrawn in part — 2026-09-23 (Part III, `fix/e2-window-units`).** Every `duration_min` result in "
              f"this report (T2's {100 * a['share_zero']:.1f}%-zero, median-0, 0%-censored headline, and the duration panels of T3, T4, T6 "
              f"and T7) came from a units defect: the window compared a per-minute average with a per-10-minute `B_e`, i.e. 30× the "
              f"baseline, not 3×. With the confirmed units, median duration is {m(b['median'])} min, {100 * b['share_zero']:.1f}% exactly 0, "
              f"{n(fx['n_censored'])} censored (n = {n(b['n'])}). See `results/fundamental_exploration/e2/UNITS_FIX.md`. The momentum "
              f"results are unaffected. The text below is left as the record.\n{BANNER_END}\n\n")
    for path in ("results/fundamental_exploration/e2/REPORT.md", "results/reports/fundamental_exploration_e2_report.md"):
        with open(path, encoding="utf-8") as f:
            s = f.read()
        if BANNER_START in s:
            s = s[:s.index(BANNER_START)] + s[s.index(BANNER_END) + len(BANNER_END) + 2:]
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(banner + s)
    print(f"wrote {OUT} ({len(L)} lines); banner on 2 reports; momentum checks {checks}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
