"""
Brief 1 -- REPORT.md, generated from artifacts (Amendment 1 A1.6; II.5 "every count in REPORT.md is read
from an artifact by code at report-build time, not typed").

Every number below is formatted from an artifact read in this script. The fixed prose says what each
number is and where it comes from; it describes the pictures and interprets nothing (brief T7). Writes
results/attention_excursion/b1/REPORT.md and the copy at results/reports/attention_excursion_b1_report.md.

Usage: .venv/Scripts/python.exe research/attention_excursion_b1/build_report.py
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C  # noqa: E402

A = C.REPO / C.ART


def J(name):
    p = A / name
    return json.load(open(p, encoding="utf-8")) if p.exists() else None


def n(x):
    return f"{int(x):,}" if x is not None else "—"


def pct(x, d=1):
    return f"{100 * x:.{d}f}%" if x is not None else "—"


def f(x, d=2):
    return f"{x:,.{d}f}" if isinstance(x, (int, float)) and x == x else "—"


def yes(b):
    return "**FIRED**" if b else "clear"


def git_head():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=C.REPO, text=True).strip()
    except Exception:
        return "?"


def charts_list():
    root = C.REPO / C.CHARTS
    out = []
    for task in sorted(os.listdir(root)) if root.exists() else []:
        files = [p for p in (root / task).rglob("*.html")]
        out.append((task, len(files), sorted(str(p.relative_to(C.REPO)).replace("\\", "/") for p in files)[:6]))
    return out


def main() -> int:
    cfg = C.load_cfg()
    t0, t12, t3, t4, t5, t5b, t6 = (J("t0_population.json"), J("t1_t2_summary.json"), J("t3_open_boundary.json"),
                                    J("t4_summary.json"), J("t5_summary.json"), J("t5b_summary.json"), J("t6_controls.json"))
    ba = J("t5_a3_before_after.json")
    r1 = J("run1/t1_t2_summary.json")
    esc = t12["escalation"]
    stop_rows = []
    if esc["row_1"]["fires"] or esc["row_4"]["fires"]:
        status = "HARD STOP at T2 (revised escalation " + ", ".join(k for k in ("row_1", "row_4") if esc[k]["fires"]) + ")"
    elif t6 and t6["row_2"]["fires"]:
        status = "HARD STOP at T6 (escalation row 2)"
    else:
        status = "HARD STOP at T7 -- the brief's own stop, for Cooper's review"
    if t6 and t6["row_2"]["fires"]:
        stop_rows.append(f"row 2: {', '.join(t6['row_2']['failed_controls'])}")

    L = []
    w = L.append
    w("# Attention and the excursion — Brief 1 — " + status)
    w("")
    w(f"**Generated by** `research/attention_excursion_b1/build_report.py` from `results/attention_excursion/b1/artifacts/` "
      f"at `HEAD {git_head()}`; every figure below is read from an artifact at build time (II.5). "
      f"**Config** `config/attention_excursion_b1.json`, hash `{C.cfg_hash()}`. **Brief** `prompts/attention_excursion.md` (Part II; as-run record "
      f"`prompts/attention_excursion_b1.md`) as amended by `prompts/attention_excursion_b1_amendment_1.md`, "
      f"`prompts/attention_excursion_b1_amendment_2.md` and `prompts/attention_excursion_b1_amendment_3.md`. **Branch** `explore/attention-excursion-b1`. Each artifact carries the "
      f"config hash it was built under.")
    w("")
    w("Describes the pictures. No interpretation, no findings section, no recommendation (brief T7). "
      "No attention measure is put against any excursion component anywhere in this build (II.4).")
    w("")
    # ------------------------------------------------------------ escalation
    w("## 1. Escalation — every row")
    w("")
    w("| row | criterion | tier | observed | state |")
    w("|---|---|---|---|---|")
    e1, e4, e4s, e7 = esc["row_1"], esc["row_4"], esc["row_4_as_run_sensitivity"], esc["row_7"]
    w(f"| 1 | {e1['criterion']} | HARD STOP | {n(e1['n'])} of {n(e1['of'])} = {pct(e1['observed_share'], 2)} | {yes(e1['fires'])} |")
    if t6:
        r2 = t6["row_2"]
        w(f"| 2 | {r2['criterion']} | HARD STOP | failed: {', '.join(r2['failed_controls']) or 'none'} | {yes(r2['fires'])} |")
    else:
        w("| 2 | any T6 control fails its declared pass criterion | HARD STOP | — | not reached |")
    if t5:
        ct = t5["II5_causality_test"]
        w(f"| 3 | any print after τ reaches an attention quantity | HARD STOP | no assertion fired in the build; the II.5 test "
          f"({len([k for k in ct if k not in ('passes', 'clean_inputs_do_not_raise') and not k.startswith('segment_')])} functions fed a "
          f"post-τ print) raised on every one | clear |")
    else:
        w("| 3 | any print after τ reaches an attention quantity | HARD STOP | — | not reached |")
    w(f"| 4 | {e4['criterion']} | HARD STOP | {n(e4['n_outside'])} of {n(e4['of_d1'])} = {pct(e4['observed_share_of_d1'], 2)} "
      f"(below {n(e4['outside_below'])}, above {n(e4['outside_above'])}) | {yes(e4['fires'])} |")
    w(f"| 4s | {e4s['criterion']} | sensitivity (A1.1) | {n(e4s['n_outside'])} of {n(e4s['of_d1'])} = {pct(e4s['share_of_d1'], 1)} | reported |")
    if t5:
        r5 = t5["row_5"]
        w(f"| 5 | {r5['criterion']} | LOG | {n(r5['n'])} events | {'logged' if r5['n'] else 'none'} |")
    else:
        w("| 5 | shs_asof_ns ≥ tau_ns for any event | LOG | — | not reached |")
    if t4:
        r6 = t4["row_6"]
        w(f"| 6 | {r6['criterion']} | LOG | {n(r6['thin_events'])} of {n(r6['of'])} = {pct(r6['observed_share'])} | {'logged' if r6['fires'] else 'clear'} |")
    else:
        w("| 6 | thin paths above 20% of the dev sample | LOG | — | not reached |")
    w(f"| 7 | {e7['criterion']} | LOG | {n(e7['n'])} of {n(e7['of'])} = {pct(e7['observed_share'], 2)} | {'logged' if e7['fires'] else 'clear'} |")
    w("")
    # ------------------------------------------------------------ II.5
    ii = t12["verification_II5"]
    w("## 2. II.5 verification block")
    w("")
    w("| check | result | source |")
    w("|---|---|---|")
    w(f"| D1 = 15,763; dev = 50; sidecar = 6; slices partition D1 | D1 {n(t0['d1_n'])}, dev {t0['dev_n']}, sidecar {t0['sidecar_n']}; "
      f"{len(t0['assertions_passed'])} assertions passed | `t0_population.json` |")
    pm = ii["tau_ge_proxy_prime_minute_start"]
    w(f"| `tau_ns` int64; τ ≥ τ_proxy′ minute start | int64: {ii['tau_ns_int64']}; violations {n(pm['violations'])} of {n(pm['checked'])} | `t1_t2_summary.json` |")
    rv = ii["proxy_prime_construction_reproduces_v1"]
    w(f"| τ_proxy′ construction reproduces v1's stored proxy (same close) | {n(rv['within_1us'])} of {n(rv['compared'])} within 1 µs "
      f"(max error {f(rv['max_abs_err_ns'], 0)} ns) | `t1_t2_summary.json` |")
    if t5:
        w(f"| attention causality assertion wired and exercised | test passes: {t5['II5_causality_test']['passes']} | `t5_causality_test.json` |")
        ct = t5["II5_causality_test"]
        w(f"| A2 half-windows inside τ's clock segment and clear of both cross minutes (Amendment 3 A3.1) | asserted on every rung of "
          f"every event with A2 ({n(t5['events']['dev_v3_with_a2'])} dev + the sidecar), none raised; the test raises on a 04:00-anchored "
          f"regular-hours ladder ({ct.get('segment_rth_tau_anchored_0400')}) and on τ inside the opening cross "
          f"({ct.get('segment_tau_in_open_cross_minute')}), and passes a segment-anchored one "
          f"({ct.get('segment_anchored_ladder_does_not_raise')}) | `t5_causality_test.json` |")
    if t4:
        cv = t4["II5_bucket_volume_conservation"]
        w(f"| bucket volume conservation per event and rung | {n(cv['event_rungs_checked'])} event-rungs asserted; max bucket volume "
          f"relative error {cv['max_bucket_vol_rel_err']:.2e} | `t4_summary.json` |")
    if t6:
        w(f"| blindness invariance to 1e-9 | max abs Δ under ×10 / ×0.1: {t6['detail']['blindness']['rescale_max_abs_diff']:.2e}; "
          f"pass {t6['detail']['blindness']['pass']} | `t6_controls.json` |")
    w("| every REPORT.md count read from an artifact by code | this file is generated by `build_report.py` | — |")
    w("")
    # ------------------------------------------------------------ run 1
    w("## 3. Runs 1–3 — the earlier stops, and the 'before' of Amendment 3")
    w("")
    rr4 = r1["escalation"]["row_4"]
    w(f"Run 1 (`a3f6a9c`) stopped at T2 on the original row 4: τ_exact − v1 proxy outside [−1, 61] s on "
      f"{n(rr4['n_outside'])} of {n(rr4['of_d1'])} ({pct(rr4['observed_share_of_d1'])}). Its T1 took the largest-size {{8, 15}} print. "
      "Its artifacts are kept under `artifacts/run1/`. Amendment 1 re-specified T1 (A1.2) and row 4 (A1.1).")
    w("")
    r2 = J("run2/t6_controls.json")
    r25 = J("run2/t5_summary.json")
    if r2:
        w(f"Run 2 (`518152c`) cleared rows 1 and 4, ran T3-T6 on the bipower instrument, and stopped at T6 on row 2: failed "
          f"{', '.join(r2['row_2']['failed_controls'])}. Its T4-T6 artifacts and charts are kept under `artifacts/run2/` and "
          f"`charts/run2/` as the record of what the bipower instrument produced (A2.10); its A2 ladder, which stopped at the first "
          f"failing rung, gave zero valid rungs on {n(r25['a2']['valid_rungs_distribution'].get('0.0', 0))} of "
          f"{n(r25['events']['dev_v3_with_attention'])} dev events. Amendment 2 changed the noise scale to realised variance (A2.1), "
          "derived the control references by simulation (A2.2), added the peak tie rule (A2.3), judged every A2 rung on its own (A2.4), "
          "left the W ≥ L competition cells undefined (A2.5) and re-derived the halt flag (A2.6); T1-T3 were not re-run.")
        w("")
    r3 = J("run3/t6_controls.json")
    if r3:
        w(f"Run 3 (`99b7e51`, Amendment 2) passed all {len(r3['verdict'])} T6 controls and stopped at T7. Amendment 3 anchored the A2 "
          "ladder at the start of τ's clock segment (A3.1), made τ inside a cross minute a class with no A2 (A3.2), retired DA-4 and "
          "`open_adjacent_0930` (A3.3), and matched the T5b control on the octave since i's own crossing and the clock segment (A3.5). "
          "Run 3's T5, T5b and T6 artifacts and charts are kept under `artifacts/run3/` and `charts/run3/` as the 'before'. **T4 below is "
          "run 3's (T4 does not re-run, A3.7); T5, T5b and T6 are the Amendment 3 run.**")
        w("")
    # ------------------------------------------------------------ T0
    w("## 4. T0 — population, slices, D38")
    w("")
    b, a = t0["slice_counts_before_quarantine"], t0["slice_counts_after_quarantine"]
    w("| slice | before quarantine | after quarantine | first-seen events | distinct tickers |")
    w("|---|---|---|---|---|")
    for s in ("development", "selection", "final"):
        w(f"| {s} | {n(b[s])} | {n(a[s])} | {n(t0['first_seen_events_per_slice'][s])} ({pct(t0['first_seen_share'][s])}) | "
          f"{n(t0['distinct_tickers_per_slice'][s])} |")
    w(f"| dev_quarantine | — | {n(a['dev_quarantine'])} | — | — |")
    w("")
    w("D38 appended verbatim to `docs/Universe-Decisions.md`, CLAUDE.md index → D39 (`dec1d70`); the standing line "
      "\"Ticker-blocked splits\" now carries the D38 exception (A1.6).")
    w("")
    # ------------------------------------------------------------ T1
    t1 = t12["t1"]
    w("## 5. T1 — prior close, A1.2 precedence")
    w("")
    w("| source | n |")
    w("|---|---|")
    for k, v in t1["source_counts"].items():
        w(f"| `{k}` | {n(v)} |")
    w(f"| coverage | {n(t1['coverage']['available'])} of {n(t1['coverage']['of'])} ({pct(t1['coverage']['share'], 2)}) |")
    w("")
    w(f"Listing venue from the Phase 1b snapshot: {', '.join(f'{k} {n(v)}' for k, v in t1['listing_by_mic'].items())}; "
      f"listing unknown {n(t1['listing_unknown'])}. MIC → exchange id {cfg['t1_prior_close']['listing_venue']['mic_to_exchange_id']} "
      "(census-derived; XASE → 1 inferred, not verified). Codes by meaning: 8 = Closing Prints (cross), 15 = Market Center "
      "Official Close.")
    w("")
    lm = t1["listing_venue_mismatch"]
    w(f"`listing_venue_mismatch` (no cross on the snapshot venue, a cross on another listing venue): **{n(lm['n'])}** events — "
      f"by snapshot venue {lm['by_mic']}; venues that crossed {lm['cross_venues_seen']}; resolved as {lm['resolved_as']}.")
    w("")
    q1, qm = t1["revised_minus_run1_bp"], t1["abs_revised_minus_minute_bar_bp"]
    w(f"Revised − run-1 close: n {n(q1['n'])}, equal {n(t1['revised_equals_run1'])}, p05 {f(q1['p05'], 1)} bp, "
      f"median {f(q1['p50'], 1)}, p95 {f(q1['p95'], 1)}, min {f(q1['min'], 0)}, max {f(q1['max'], 0)}. "
      f"|Revised − minute-bar close|: n {n(qm['n'])}, equal {n(t1['revised_equals_minute_bar'])}, median {f(qm['p50'], 1)} bp, "
      f"p75 {f(qm['p75'], 1)}, p95 {f(qm['p95'], 1)}, p99 {f(qm['p99'], 1)}.")
    w("")
    ov = t1["run1_other_venue_picks"]
    w(f"Run 1's {n(ov['n'])} other-venue picks now resolve as {ov['now_resolve_as']}; {n(ov['now_equal_run1_code8_price'])} "
      f"now equal the code-8 price run 1 passed over. Events carrying code 38 on the prior session: {n(t1['code38_events'])} (counted, not used).")
    w("")
    w("→ `charts/t1/01_revised_close_vs_minute_bar.html`, `charts/t1/02_revised_close_vs_run1.html`")
    w("")
    # ------------------------------------------------------------ T2
    t2 = t12["t2"]
    w("## 6. T2 — τ on all of D1")
    w("")
    w(f"τ available {n(t2['tau_available']['n'])} of {n(t2['tau_available']['of'])} ({pct(t2['tau_available']['share'], 2)}); "
      f"reasons {t2['tau_reasons']}. Segment {t2['segment']}. A12 `flag_cross_session_extreme` flagged on "
      f"{n(t2['a12_flag']['flagged'])} (missing {n(t2['a12_flag']['flag_missing'])}).")
    w("")
    q4 = t2["row4_d_exact_minus_proxy_prime_s"]
    w(f"Row 4 distribution, τ_exact − τ_proxy′ (s): n {n(q4['n'])}, min {f(q4['min'])}, p50 {f(q4['p50'])}, p95 {f(q4['p95'])}, "
      f"p99 {f(q4['p99'])}, max {f(q4['max'])}. Outside-band cause: {e4['cause']}.")
    qs = t2["as_run_d_exact_minus_proxy_v1_s"]
    w(f"As-run sensitivity, τ_exact − v1 stored proxy (s): n {n(qs['n'])}, p01 {f(qs['p01'])}, p50 {f(qs['p50'])}, p99 {f(qs['p99'])}.")
    w("")
    sg = t2["spike_guard"]
    w(f"Spike guard (3% / 3%): τ moved on {n(sg['events_tau_moved'])} events (move median {f(sg['move_s'].get('p50'))} s, "
      f"p95 {f(sg['move_s'].get('p95'), 0)} s); events with any spike skipped {n(sg['events_with_any_spike_skipped'])}; "
      f"τ differs under the overlay's 1.5% agreement on {n(sg['tau_differs_under_guard15'])} (A1.4).")
    w("")
    tc = t2["tau_close_sensitive"]
    qg = tc["tau_gap_close_s"]
    w(f"`tau_close_sensitive` (A1.3, > 60 s): TRUE {n(tc['true'])}, FALSE {n(tc['false'])}, NULL {n(tc['null'])}; one close "
      f"crosses and the other does not on {n(tc['one_side_only'])}; τ identical under both closes on {n(tc['tau_equal_under_both_closes'])}. "
      f"Gap: p01 {f(qg.get('p01'), 0)} s, p50 {f(qg.get('p50'))} s, p99 {f(qg.get('p99'), 0)} s.")
    w("")
    w("→ `charts/t2/01_row4_tau_exact_minus_proxy_prime.html`, `02_spike_guard_moves.html`, `03_tau_close_gap.html`")
    w("")
    if t3:
        w("## 7. T3 — the open profile (DA-4 retired by Amendment 3)")
        w("")
        w(f"{n(t3['events_used'])} D1 events; excluded (prior close unavailable) {n(t3['events_excluded_prior_close_unavailable'])}; "
          f"never crossing, all minutes included {n(t3['events_never_crossing_all_minutes_included'])}; minute_index vs clock-minute "
          f"mismatches before 10:30: {n(t3['minute_index_vs_clock_minute_mismatch_before_1030'])} of {n(t3['bars_before_1030'])} bars. "
          f"{t3['pre_0400']}.")
        w("")
        w("| open | proposed boundary (first minute) | minutes after open | n events at it | 5-consecutive variant |")
        w("|---|---|---|---|---|")
        for o, p in t3["proposals"].items():
            a1, a5 = p["proposed_boundary_first_minute"], p["proposed_boundary_5_consecutive"]
            w(f"| {o} | {a1['clock_et'] if a1 else 'none'} | {a1['minutes_after_open'] if a1 else '—'} | {n(a1['n_events']) if a1 else '—'} | "
              f"{(a5['clock_et'] + ' (+' + str(a5['minutes_after_open']) + ')') if a5 else 'none'} |")
        w("")
        import pandas as _pd
        prof = _pd.read_parquet(A / "t3_open_profile.parquet").set_index("clock_et")
        for o in ("04:00", "09:30"):
            nxt = prof.index[prof.index.get_loc(o) + 1]
            r0, r1 = prof.loc[o], prof.loc[nxt]
            w(f"- At {o}: median {f(r0['median'], 3)}, IQR [{f(r0['p25'], 3)}, {f(r0['p75'], 3)}], reference level "
              f"{f(r0['L_ref_10_20'], 3)}, n {n(r0['n_events'])}; at {nxt}: median {f(r1['median'], 3)}, IQR "
              f"[{f(r1['p25'], 3)}, {f(r1['p75'], 3)}]. The declared rule is satisfied at the open minute itself because "
              f"the reference level lies inside that minute's IQR.")
        w("")
        w("**Amendment 3 A3.3:** the open-adjacent boundary (DA-4), its `open_adjacent_0930` column and its pending state are retired; "
          "the A2 ladder is anchored at the start of τ's clock segment instead (§9a). `sec_from_0930` stays as a descriptor. "
          "`t4_excursion.parquet` still carries the retired column (all NULL) because T4 does not re-run (A3.7); nothing reads it.")
        w("")
        w("→ `charts/t3/01_open_profile_0400.html`, `02_open_profile_0930.html`")
        w("")
    if t4:
        w("## 8. T4 — the excursion vector, dev sample (unconditional)")
        w("")
        w(f"Events: dev {t4['events']['dev_v3']}, sidecar {t4['events']['sidecar']} (own rows, never pooled). Vector available by rung "
          f"{t4['vector_available_rows']}; unavailable reasons {t4['unavailable_reasons'] or 'none'}. Path prints after τ: dev median "
          f"{n(t4['path_prints']['dev_median'])}, min {n(t4['path_prints']['dev_min'])}.")
        w("")
        md = t4["component_medians"].get("dev_v3", {})
        w(f"Noise scale: {t4['scale']} -- `sigma_path` = sqrt(sum of squared bucket log returns); bipower is carried as "
          "`sigma_bv_path_bp` and `jump_share` = 1 − BV/RV, descriptors only.")
        w("")
        comps = ["u_peak", "rise_s", "fall_s", "dip_before_peak_s", "terminal_s", "sigma_b_bp", "sigma_path_bp", "sigma_bv_path_bp",
                 "jump_share", "peak_tie_span_u", "rise_bp", "fall_bp", "rise_cents", "fall_cents", "t_peak_s", "t_end_s"]
        w("| component (median, dev) | " + " | ".join(f"N={N}" for N in md) + " |")
        w("|---|" + "---|" * len(md))
        for c in comps:
            w(f"| `{c}` | " + " | ".join(f(md[N][c], 3 if c in ('u_peak', 'rise_s', 'fall_s', 'dip_before_peak_s', 'terminal_s', 'jump_share', 'peak_tie_span_u') else 1) for N in md) + " |")
        w("| n | " + " | ".join(n(md[N]["n"]) for N in md) + " |")
        w("")
        ec = t4["edge_classes"].get("dev_v3", {})
        w("| edge class (dev, count) | " + " | ".join(f"N={N}" for N in ec) + " |")
        w("|---|" + "---|" * len(ec))
        for k in ["rise_censored", "no_rise", "peak_at_tau", "peak_tied", "halt_in_path", "halt_gap_rth", "halt_label_in_path", "thin_path", "sigma_zero"]:
            w(f"| `{k}` | " + " | ".join(n(ec[N][k]) for N in ec) + " |")
        w("")
        gd = t4["gaps_dev"]
        w(f"Halt rule (A2.6): a path gap of at least 300 s inside regular hours, or an LULD-V3c label. Flagged on "
          f"{n(gd['halt_in_path_events'])} dev events (labels available for {n(gd['halt_label_available_events'])}). Median largest gap "
          f"inside regular hours {f(gd['max_gap_in_rth_s_median'], 0)} s; median largest gap outside regular hours "
          f"{f(gd['max_gap_outside_rth_s_median'], 0)} s (`max_gap_outside_rth_s`, a descriptor, not a halt).")
        w("")
        w("→ `charts/t4/strips_by_event.html` (one chart with an event selector: each dev and sidecar event's bucketed path, all "
          "three rungs), `charts/t4/u_peak_N{50,100,200}.html` (the simulated discrete free-walk reference drawn, A2.2)")
        w("")
    if t5:
        w("## 9. T5 — the attention axes, dev sample")
        w("")
        a1 = t5["a1"]
        w(f"**A1 turnover** — states {a1['state']}; turnover median {a1['turnover']['median']:.4g} (p25 {a1['turnover']['p25']:.4g}, "
          f"p75 {a1['turnover']['p75']:.4g}, n {n(a1['turnover']['n'])}); share-count suspect {n(a1['share_count_suspect'])}; "
          f"dilution form before t0 {n(a1['dilution_form_before_t0'])}; share count accepted after τ (stricter check, logged) "
          f"{n(a1['shs_accepted_after_tau'])}. Row 5 (asof ≥ τ): {n(t5['row_5']['n'])}.")
        w("")
        a2 = t5["a2"]
        sgm = t5["segments"]
        w(f"**A2 anchoring (Amendment 3)** — dev events by τ segment {sgm['dev_v3_by_segment']}; A2 computed on "
          f"{n(t5['events']['dev_v3_with_a2'])} of {n(t5['events']['dev_v3_with_attention'])}; τ in a cross minute (A2 unavailable, "
          f"a label) {n(sgm['dev_v3_auction_minute'])}. By segment: " + "; ".join(
              f"{sg}: {n(v['events'])} events, median {f(v['valid_rungs_median'], 1)} valid rungs, {n(v['zero_valid'])} with none, "
              f"median H {f(v['H_s_median'], 0)} s" for sg, v in a2["by_segment"].items()) + ". A1 turnover still counts every share "
          "from 04:00 (A3.3).")
        w("")
        w(f"**A2 acceleration** ({a2['rule']}) — valid rungs per event {a2['valid_rungs_distribution']} (median "
          f"{f(a2['valid_rungs_median'], 1)}); first valid rung {a2['first_valid_k_distribution']}; events whose valid rungs form one "
          f"contiguous run {n(a2['valid_contiguous_events'])}. Invalid rungs by class {a2['invalid_rung_classes']}; the D22 floor was "
          f"binding on {n(a2['resolution_floor_ever_binding'])} rungs (pre-registered expectation: never); rung 0 is `from_nothing` on "
          f"{n(a2['rung0_from_nothing_events'])} events. Kernel check defined on {n(a2['kernel_defined_valid_rungs'])} of "
          f"{n(a2['valid_rungs_total'])} valid rungs (k ≥ 2 by the edge rule).")
        w("")
        w(f"Events with **zero** valid rungs: {n(a2['zero_valid_rung_events'])} of {n(t5['events']['dev_v3_with_a2'])} with A2. "
          f"Most common valid-rung patterns: {a2['valid_pattern_top']}.")
        w("")
        w("| rung k | n (both versions) | Spearman count vs kernel |")
        w("|---|---|---|")
        for k, v in a2["spearman_count_vs_kernel_by_rung"].items():
            w(f"| {k} | {n(v['n'])} | {f(v['spearman_count_vs_kernel'], 3)} |")
        w("")
        a3 = t5["a3"]
        w(f"**A3 filings (relative to τ)** — available {n(a3['available'])}; filing within 24 h before τ {n(a3['filing_24h'])}; "
          f"median hours since last filing {f(a3['hours_since_last_filing_median'], 1)}; F1's t0 before τ on {n(a3['t0_before_tau'])}, "
          f"after τ on {n(a3['t0_after_tau'])} (why the τ-relative rebuild was needed).")
        w("")
        w("**Cross-sectional axis** — live-set size per liveness (dev events): " +
          "; ".join(f"L={L}: {v['live_n_distribution']} (alone {n(v['alone_events'])}; no rung window: {v.get('reason_no_window', {})})"
                    for L, v in t5["cross_sectional"].items()) + ". `flow_share` and `accel_rank` are taken over j's segment-anchored "
          "rung windows, identical clock windows for every live name (A3.4).")
        w("")
        w("→ `charts/t5/a2_curves_by_event.html` (one chart with an event selector: count and kernel overlaid, invalid rungs marked), "
          "`charts/t5/valid_rungs.html` (by segment)")
        w("")
    if ba:
        w("## 9a. Amendment 3 — the weight of the anchoring change (A3.7)")
        w("")
        w(f"Before = run 3 (`artifacts/run3/`), every ladder anchored at 04:00. After = this run, anchored at the start of τ's clock "
          f"segment (04:00, open + 60 s, close + 60 s, from the XNYS calendar). {n(ba['events'])} dev events, by clock segment of τ. "
          "Built by `t5_a3_before_after.py`.")
        w("")
        w("| τ segment | events | valid rungs before: median · total · zero-valid events | after: events with A2 · median · total · zero-valid | "
          "previously valid rungs straddling the open | median H before → after (s) |")
        w("|---|---|---|---|---|---|")
        for sg, v in ba["valid_rungs_by_segment"].items():
            b_, a_ = v["before"], v["after"]
            w(f"| {sg} | {n(v['events'])} | {f(b_['valid_rungs_median'], 1)} · {n(b_['valid_rungs_total'])} · {n(b_['zero_valid_events'])} | "
              f"{n(a_['events_with_a2'])} · {f(a_['valid_rungs_median'], 1)} · {n(a_['valid_rungs_total'])} · {n(a_['zero_valid_events'])} | "
              f"{n(b_['valid_rungs_straddling_open'])} | {f(b_['H_median_s'], 0)} → {f(a_['H_median_s'], 0)} |")
        va = ba["valid_rungs_all"]
        w(f"| all | {n(ba['events'])} | {f(va['before_median'], 1)} · {n(va['before_total'])} · {n(va['before_zero_valid_events'])} | "
          f"— · {f(va['after_median_events_with_a2'], 1)} · {n(va['after_total'])} · {n(va['after_zero_valid_events'])} | "
          f"{n(ba['previously_valid_rungs_straddling_open']['rungs'])} | — |")
        w("")
        so, sc = ba["previously_valid_rungs_straddling_open"], ba["previously_invalid_rungs_straddling_open"]
        w(f"**Previously valid rungs that straddled the open** ({so['rule']}): {n(so['rungs'])} of {n(so['of_valid_rungs'])} valid rungs, "
          f"on {n(so['events'])} events. Previously invalid rungs straddling the open: {n(sc['rungs'])}, by class {sc['by_class']}. "
          f"Previously valid rungs straddling the close: {n(ba['previously_valid_rungs_straddling_close']['rungs'])} "
          f"on {n(ba['previously_valid_rungs_straddling_close']['events'])} events.")
        w("")
        fn = ba["from_nothing"]
        w(f"**`from_nothing`**: {n(fn['before_rungs'])} rungs before → {n(fn['after_rungs'])} after (by τ segment: before "
          f"{fn['before_by_segment']}, after {fn['after_by_segment'] or '{}'}); rung 0 `from_nothing` on {n(fn['before_rung0_events'])} "
          f"events before → {n(fn['after_rung0_events'])} after. Invalid classes before {ba['invalid_classes']['before']}, after "
          f"{ba['invalid_classes']['after']}. By rung k, before {fn['before_by_k']}; after {fn['after_by_k']}. Median half-window of a "
          f"`from_nothing` rung: {f(fn['before_half_window_s_median'], 3)} s before, {f(fn['after_half_window_s_median'], 3)} s after; "
          f"`from_nothing` rungs that straddled the open before: {n(fn['before_straddling_open'])}.")
        w("")
        am = ba["auction_minute_class"]
        w(f"**Cross-minute class (A3.2)**: on D1, τ in the opening-cross minute {n(am['d1_auction_open'])} and in the closing-cross "
          f"minute {n(am['d1_auction_close'])} of {n(am['d1_tau_available'])} events with τ (brief's figure: {am['brief_figure']}); "
          f"all D1 by segment {am['d1_by_segment']}; early-close dates in D1 {n(am['early_close_dates_in_d1'])}. Dev sample: "
          f"{n(am['dev_v3'])} ({', '.join(am['dev_v3_ids']) or 'none'}); sidecar: {n(t5['segments']['sidecar_auction_minute'])}.")
        w("")
        pm = ba["premarket_ladders_identical"]
        w(f"Check: premarket crossers' ladders identical in both runs ({pm['why']}): **{pm['value']}** on {n(pm['events'])} events.")
        w("")
        w("→ `charts/t5/valid_rungs_before_after.html` (every event, before and after, by segment)")
        w("")
    if t5b:
        w("## 10. T5b — competition check (dev-event dates only)")
        w("")
        w(f"{t5b['dates']} dates; crossings with at least one live name {n(t5b['crossings_with_any_live_name'])}. Control (Amendment 3 "
          f"A3.5): {t5b['control_rule']}")
        w("")
        w("**Matched-control counts per cell** (pairs = (live name i, crossing j)):")
        w("")
        w("| liveness · W | pairs | with ≥ 1 matched control | `no_match` | no_match reasons | not attempted: crossing window outside 04:00–20:00 | "
          "matched moments drawn | median eligible moments |")
        w("|---|---|---|---|---|---|---|---|")
        for k, v in t5b["cells"].items():
            m_ = v["matching"]
            na_ = m_["pairs"] - m_["pairs_with_matched_control"] - m_["pairs_no_match"]
            w(f"| {k.replace('|', ' · ')} | {n(m_['pairs'])} | {n(m_['pairs_with_matched_control'])} | {n(m_['pairs_no_match'])} | "
              f"{', '.join(f'{r} {n(c)}' for r, c in m_['no_match_reason'].items()) or '—'} | {n(na_)} | {n(m_['matched_moments_drawn'])} | "
              f"{f(m_['n_eligible_median'], 0)} |")
        w("")
        w("`structural_octave_bin_not_wider_than_W`: τ_j lies inside its own octave bin, so when the bin is no wider than W every moment "
          "in it is within W of τ_j and is excluded -- `no_match` by construction, as W ≥ L is (A2.5).")
        w("")
        w("| liveness · W | crossing, all pairs: n, median log-ratio (p25, p75) | crossing, pairs with a matched control | matched control | "
          "windows crossing a segment boundary: crossing · control |")
        w("|---|---|---|---|---|")
        fmt = lambda x: (f"{n(x['n_ok'])}, {f(x['median'], 3)} ({f(x['p25'], 3)}, {f(x['p75'], 3)})" if x and x.get("median") is not None
                         else (f"none -- {x.get('status')}" if x and x.get("status") else "—"))  # noqa: E731
        for k, v in t5b["cells"].items():
            cr, co, cm = v.get("crossing", {}), v.get("control", {}), v.get("crossing_matched_pairs", {})
            w(f"| {k.replace('|', ' · ')} | {fmt(cr)} | {fmt(cm)} | {fmt(co)} | {n(cr.get('window_crosses_segment'))} · "
              f"{n(co.get('window_crosses_segment'))} |")
        w("")
        b5 = J("run3/t5b_summary.json")
        if b5:
            w("Run 3's uniform control, for reference (median log-ratio, crossing vs control): " + "; ".join(
                f"{k.replace('|', ' · ')}: {f(v['crossing']['median'], 3)} vs {f(v['control']['median'], 3)}"
                for k, v in b5["cells"].items() if v.get("crossing", {}).get("median") is not None and v.get("control", {}).get("median") is not None) + ".")
            w("")
        w(f"Structurally undefined and not run -- {t5b['undefined_rule']}: "
          + "; ".join(f"L={L}: W = {ws}" for L, ws in t5b["structurally_undefined_cells"].items() if ws) + ".")
        w("")
        w("→ `charts/t5b/competition_W{5,15,60}.html`, `charts/t5b/matched_control_counts.html`")
        w("")
    if t6:
        v, d = t6["verdict"], t6["detail"]
        w("## 11. T6 — the four controls (pass criteria from the config, committed before the run)")
        w("")
        w("| control | verdict |")
        w("|---|---|")
        for k, x in v.items():
            w(f"| {k} | **{'PASS' if x else 'FAIL'}** |")
        w("")
        w("**Negative, excursion** (Amendment 2 A2.2; references simulated at each N and committed before the run, "
          "`t6_references.json`): pass = two-sample KS to the simulated reference ≤ 0.05 and |mean rise_s − reference| ≤ 0.05, every rung.")
        w("")
        w("| construction | rung | n | KS vs simulated reference | KS vs continuous arcsine (descriptive) | mean rise_s | reference | Δ | pass |")
        w("|---|---|---|---|---|---|---|---|---|")
        for key, lab in (("negative_excursion_bridge", "bridge (demeaned shuffles)"), ("negative_excursion_free_walk", "free walk (draws with replacement)")):
            for N, x in d[key].items():
                w(f"| {lab} | {N} | {n(x['n'])} | {f(x['ks_vs_simulated_reference'], 3)} | {f(x['ks_vs_arcsine_continuous'], 3)} | "
                  f"{f(x['mean_rise_s'], 3)} | {f(x['reference_mean_rise_s'], 3)} | {f(x['delta_mean_rise_s'], 3)} | {x['pass']} |")
        w("")
        w("**Positive, excursion** (bridge path + injected rise 2.0 to u = 0.3 then fall 1.5, in the event's own RV `sigma_path`): pass = "
          "median recovered rise_s and fall_s within ±10% of the simulated expectation for the same injection, and median u_peak within "
          "±0.05 of it, every rung. Bias against the injected values is an instrument property, reported, never corrected.")
        w("")
        w("| rung | n | median u_peak (ref) | median rise_s (ref) | median fall_s (ref) | bias vs injected: u / rise / fall | pass |")
        w("|---|---|---|---|---|---|---|")
        for N, x in d["positive_excursion"].items():
            b_ = x["bias_vs_injected"]
            w(f"| {N} | {n(x['n'])} | {f(x['median_u_peak'], 3)} ({f(x['reference_median_u_peak'], 3)}) | {f(x['median_rise_s'], 3)} "
              f"({f(x['reference_median_rise_s'], 3)}) | {f(x['median_fall_s'], 3)} ({f(x['reference_median_fall_s'], 3)}) | "
              f"{b_['u_peak']:+.3f} / {b_['rise_s']:+.3f} / {b_['fall_s']:+.3f} | {x['pass']} |")
        w("")
        ap = d.get("acceleration_population", {})
        r3c = J("run3/t6_controls.json")
        same = r3c and all(r3c["detail"][k] == d[k] for k in ("negative_excursion_bridge", "negative_excursion_free_walk", "positive_excursion", "blindness"))
        w(f"The excursion controls and blindness re-ran unchanged under the committed seed; identical to run 3: **{bool(same)}**.")
        w("")
        w(f"**Acceleration controls (Amendment 3)** — synthetic tapes over each event's segment history {ap.get('history', '')}, with the "
          f"event's own collapsed count there: {n(ap.get('events'))} events ({ap.get('segments')}); excluded, τ in a cross minute "
          f"{n(ap.get('excluded_auction_minute'))}.")
        w("")
        w("**Negative, acceleration** (|median| < 0.1 and SD(z) in [0.80, 1.25], readable rungs):")
        w("")
        w("| rung k | n | median accel | SD(z) | readable | pass |")
        w("|---|---|---|---|---|---|")
        for k, x in d["negative_acceleration"].items():
            w(f"| {k} | {n(x['n'])} | {f(x['median_accel'], 4)} | {f(x['sd_z'], 3)} | {x['readable']} | {x['pass']} |")
        w("")
        w("**Positive, acceleration** (step at the midpoint of rung m; verdict on k ≥ m; k < m reported against ln(1 + 2^(k−m))):")
        w("")
        w("| m, k | n | median accel | expected | role | pass vs expected | pass vs literal text |")
        w("|---|---|---|---|---|---|---|")
        for k, x in d["positive_acceleration"].items():
            w(f"| {k} | {n(x['n'])} | {f(x['median_accel'], 3)} | {f(x['target'], 3)} | {x['role']} | {x['pass_vs_target']} | {x['pass_literal_text']} |")
        w("")
        sw = d["null_parameter_sweep"]
        w("**Null-parameter sweep** — excursion component medians across rungs; label per config rule:")
        w("")
        w("| component | N=50 | N=100 | N=200 | label |")
        w("|---|---|---|---|---|")
        for c, x in sw["excursion"].items():
            m_ = x["medians"]
            w(f"| `{c}` | {f(m_['50'], 3)} | {f(m_['100'], 3)} | {f(m_['200'], 3)} | {x['label']} |")
        w("")
        w("A2 count vs kernel per rung: " + "; ".join(f"k={k}: n {x['n']}, median count {f(x['median_count'], 3)}, "
                                                        f"median kernel {f(x['median_kernel'], 3)}, Spearman {f(x['spearman'], 3)}"
                                                        for k, x in sw["a2_count_vs_kernel"].items()) + ".")
        w("")
        bl = d["blindness"]
        w(f"**Blindness** — max abs Δ under ×10 / ×0.1 {bl['rescale_max_abs_diff']:.2e} over {n(bl['rescale_checks'])} checks "
          f"(pass {bl['pass']}). Rounding sub-$1 prices to $0.01: {n(bl['rounding']['sub_dollar_events'])} sub-dollar events; "
          f"median abs Δ {json.dumps({k: round(v, 4) for k, v in bl['rounding']['median_abs_change_sub_dollar'].items()})}; "
          f"events at or above $1 unchanged: {bl['rounding']['unchanged_at_or_above_1_dollar']}.")
        w("")
        bd = J("t6_blindness_failures.json")
        if bd and bd["failed_checks"]:
            w(f"Blindness failures ({n(bd['failed_checks'])} of {n(bd['checks'])} checks; `t6_blindness_failures.json`, "
              f"`t6_blindness_diagnosis.py`): " + "; ".join(
                  f"{x['event_id']} N={x['N']} x{x['factor']:g}: i_peak {x['i_peak_original']} -> {x['i_peak_rescaled']}, "
                  f"{len(x['positions_tied_at_the_top_original'])} positions tied at the top of the original path, moved "
                  + ", ".join(f"{c} {v[0]:.4g} -> {v[1]:.4g}" for c, v in x['components_moved'].items())
                  for x in bd["failures"]) +
              f". Largest difference among the passing checks: {bd['max_abs_diff_among_passing_checks']:.2e}. "
              "Diagnosed, not fixed.")
            w("")
        w("→ `charts/t6/negative_excursion_bridge.html`, `negative_excursion_free_walk.html`, `negative_acceleration.html`, `positive_excursion.html`, "
          "`positive_acceleration.html`, `null_parameter_sweep.html`, `blindness.html`")
        w("")
    # ------------------------------------------------------------ charts & files
    w("## 12. Charts (all under `results/attention_excursion/b1/charts/`, dark theme, one per file, Plotly inlined -- A2.8, D14)")
    w("")
    w("`run1/` and `run2/` hold the charts of the two stopped runs as committed record; they were rendered by the code of their "
      "time and still load Plotly from the CDN (a `README.md` in each says so, A3.6). `run3/` holds the Amendment 2 run's T5, T5b "
      "and T6 charts (inlined).")
    w("")
    for task, cnt, _ in charts_list():
        w(f"- `{task}/` — {cnt} file(s)")
    w("")
    w("## 13. Recorded, not acted on (A1.8)")
    w("")
    w(f"Every earlier `move_at` (R0-T0c, v0, v1, v2, the exit overlay) used the minute-bar prior close, which differs from the "
      f"revised close by a median of {f(qm['p50'], 1)} bp (p95 {f(qm['p95'], 1)} bp) on this run. Those results are not re-run; "
      "their +30% membership and `move_at` carry this basis difference, whose direction on their findings has not been assessed.")
    w("")
    txt = "\n".join(L) + "\n"
    out = C.REPO / C.OUT / "REPORT.md"
    out.write_text(txt, encoding="utf-8", newline="\n")
    shutil.copyfile(out, C.REPO / "results" / "reports" / "attention_excursion_b1_report.md")
    print(f"REPORT.md written ({len(L)} lines): {status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
