"""
Shape atlas S1 -- REPORT.md, generated from artifacts. Describes the pictures: no interpretation, no
findings section (section 8). Opens with coverage and the assertions, then sections 3-6 in order.
Every number is read from an artifact here.

Writes results/shape_atlas/s1/REPORT.md and results/reports/shape_atlas_s1_report.md.

Usage: .venv/Scripts/python.exe research/shape_atlas_s1/build_report.py
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import s1common as S  # noqa: E402

VIEWS = ("post", "whole_day", "runup")


def J(name):
    return json.load(open(S.art(name), encoding="utf-8"))


def n(x):
    return f"{int(x):,}" if x is not None and x == x else "—"


def pct(x, d=1):
    return f"{100 * x:.{d}f}%" if x is not None and x == x else "—"


def f(x, d=3):
    return f"{x:,.{d}f}" if isinstance(x, (int, float, np.floating)) and x == x else "—"


def head():
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=S.REPO, text=True).strip()
    except Exception:
        return "?"


def iqr(v):
    v = pd.to_numeric(pd.Series(v), errors="coerce").dropna()
    return f"{f(v.median())} ({f(v.quantile(.25))}, {f(v.quantile(.75))}; n {n(v.size)})" if v.size else "—"


def main() -> int:
    cfg = S.load_cfg()
    t1, t2, t4, t5 = J("t1_summary.json"), J("t2_summary.json"), J("t4_summary.json"), J("t5_summary.json")
    L = []
    w = L.append
    w("# Shape atlas S1 — what kinds of path do momentum events make? — STOP (section 8) for Cooper to read the atlas")
    w("")
    w(f"*{cfg['header_line']}*")
    w("")
    w(f"**Generated by** `research/shape_atlas_s1/build_report.py` from `results/shape_atlas/s1/artifacts/` at `HEAD {head()}`; every "
      f"number below is read from an artifact. **Config** `config/shape_atlas_s1.json`, hash `{S.cfg_hash()}` (reproducibility only). "
      "**Brief** `prompts/shape_atlas_s1.md`. **Branch** `explore/shape-atlas-s1`. Reuses b2's τ, excursion vectors, attention axes and "
      "competition artifacts as they are (b2 config `69d4088aec2c`). D38 slices are ignored. The F1-layer columns in section 6 are "
      "described under **D39** (an exploratory exception to D32, Cooper 2026-09-27); section 4c's across-time check is also run "
      "ticker-blocked (same approval).")
    w("")
    w("Describes the pictures. No interpretation, no findings section.")
    w("")
    # ------------------------------------------------ coverage and assertions
    c, a = t1["coverage"], t1["assertions"]
    w("## 1. Coverage and assertions")
    w("")
    w(f"{n(t1['events'])} events with τ (all of D1 with τ). One tick pass, {t1['seconds']:,.0f} s.")
    w("")
    w("| view | available | not available (reasons) |")
    w("|---|---|---|")
    for N in ("50", "100", "200"):
        w(f"| post-τ, N = {N} | {n(c['post'][N])}; own null computed on {n(c['post_null_ok'][N])} | {n(t1['events'] - c['post'][N])} |")
    w(f"| run-up (N = 100) | {n(c['runup'])} (thin, < 250 prints: {n(c['runup_thin'])}) | {c['runup_reasons']} |")
    w(f"| whole day (N = 100) | {n(c['whole_day'])} | {c['whole_reasons'] or 'none'} |")
    w("")
    pc = a["post_components_equal_b2"]
    w("| assertion (a failure is a stop) | result |")
    w("|---|---|")
    w(f"| bucket volume conservation in every view | {a['bucket_volume_conservation']}; max bucket-volume relative error "
      + ", ".join(f"{k} {v:.1e}" for k, v in a["max_bucket_vol_rel_err"].items()) + " |")
    w(f"| every resampled path has exactly G points | {a['resampled_paths_have_G_points']} |")
    w(f"| `tau_ns` int64 | {a['tau_ns_int64']} |")
    w(f"| null paths go through the identical code path (identity index, no demeaning, output identical) | {a['null_identity_test']} |")
    w(f"| null draws are row-stable (the first r of 200 = a request for r) | {a['null_draws_row_stable']} |")
    w(f"| post-τ components equal b2's ({pc['rule'].replace('|', '')}) | {pc['passes']} (max {pc['max_diff']:.1e}) |")
    w("")
    # ------------------------------------------------ 3. theory types
    sh = pd.read_parquet(S.art("t2_theory_shares.parquet"))
    w("## 2. Theory types (section 3) — real share vs the share noise alone produces")
    w("")
    w("Rules declared before the run, first match wins, on each event's own null percentiles: " +
      "; ".join(f"**{k}** {v}" for k, v in cfg["theory_types"]["rules"].items()) + ".")
    w("")
    w("| type | " + " | ".join(f"N={N}: real (n) · null" for N in (50, 100, 200)) + " |")
    w("|---|---|---|---|")
    al = sh[sh["facet"] == "all"]
    for ty in S.TYPES:
        cells = []
        for N in (50, 100, 200):
            r = al[(al["N"] == N) & (al["type"] == ty)].iloc[0]
            cells.append(f"{pct(r.real_share)} ({n(r.n_type)}) · {pct(r.null_share)}")
        w(f"| {ty} | " + " | ".join(cells) + " |")
    w("| typed events | " + " | ".join(n(al[al["N"] == N]["n_events"].iloc[0]) for N in (50, 100, 200)) + " |")
    w("")
    w("Rung agreement (same type at both rungs): " + "; ".join(f"{k} {pct(v['same_type_share'])} of {n(v['n'])}" for k, v in t2["rung_agreement"].items()) + ".")
    w("")
    for facet in ("year", "tau_anchor_segment", "price_tier"):
        g = sh[(sh["N"] == 100) & (sh["facet"] == facet)]
        levels = list(dict.fromkeys(g["level"]))
        w(f"By {facet}, N = 100 — real · null (n typed):")
        w("")
        w("| type | " + " | ".join(f"{lv} (n {n(g[g['level'] == lv]['n_events'].iloc[0])})" for lv in levels) + " |")
        w("|---|" + "---|" * len(levels))
        for ty in S.TYPES:
            w(f"| {ty} | " + " | ".join(f"{pct(g[(g['level'] == lv) & (g['type'] == ty)]['real_share'].iloc[0])} · "
                                        f"{pct(g[(g['level'] == lv) & (g['type'] == ty)]['null_share'].iloc[0])}" for lv in levels) + " |")
        w("")
    w("→ `charts/theory_types.html` (selector: every rung × facet level), `charts/joint_peak_rise.html` (u_peak × rise_s, real vs "
      "each event's own null, by rung and year)")
    w("")
    # ------------------------------------------------ 4. data-driven types
    w("## 3. Data-driven types and whether they beat noise (section 4)")
    w("")
    for v in VIEWS:
        s = J(f"t3_{v}_summary.json")
        rmn = pd.read_parquet(S.art(f"t3_{v}_real_minus_null.parquet"))
        sp = pd.read_parquet(S.art(f"t3_{v}_spectrum.parquet"))
        rs = sp[sp["dataset"] == "real"].set_index("component")["var_share"]
        ns = sp[sp["dataset"] != "real"].groupby("component")["var_share"].mean()
        w(f"### {v} view — {n(s['events_clustered'])} events clustered ({n(s['not_clustered_sigma_zero'])} with a zero-variance path not "
          f"clustered); GMM on the first {s['d_90pct']} FPC scores (90% of the real variance); {s['null_replicates']} null replicates")
        w("")
        w("FPC variance share, components 1–5, real (null mean): " + "; ".join(f"{j}: {pct(rs[j])} ({pct(ns[j])})" for j in range(1, 6)) + ".")
        w("")
        w("| k | GMM BIC improvement real · null mean · null max | GMM silhouette real · null max | k-means silhouette real · null max | "
          "ARI GMM vs k-means real · null mean | beats null: GMM · k-means |")
        w("|---|---|---|---|---|---|")
        for r in rmn.itertuples():
            w(f"| {r.k} | {f(r.gmm_bic_improvement_real, 0)} · {f(r.gmm_bic_improvement_null_mean, 0)} · {f(r.gmm_bic_improvement_null_max, 0)} | "
              f"{f(r.gmm_silhouette_real)} · {f(r.gmm_silhouette_null_max)} | {f(r.kmeans_silhouette_real)} · {f(r.kmeans_silhouette_null_max)} | "
              f"{f(r.ari_real)} · {f(r.ari_null_mean)} | {r.gmm_beats_null} · {r.kmeans_beats_null} |")
        w("")
        st = pd.read_parquet(S.art(f"t3_{v}_stability.parquet"))
        agg = st.groupby(["method", "k", "variant", "direction"]).agg(min_corr=("centroid_corr", "min"), med_corr=("centroid_corr", "median"),
                                                                      ari=("ari_assigned_vs_refit", "first"), n_other=("n_other", "first")).reset_index()
        w("Stability across time — matched centroid correlation min / median, and ARI assigned vs refit (n assigned):")
        w("")
        w("| method | k | 2020-22 → 2023-24, tickers repeat | 2023-24 → 2020-22, tickers repeat | 2020-22 → 2023-24, ticker-blocked | "
          "2023-24 → 2020-22, ticker-blocked |")
        w("|---|---|---|---|---|---|")
        for (method, k), g in agg.groupby(["method", "k"]):
            cells = []
            for variant, direction in (("tickers_repeat", "A->B"), ("tickers_repeat", "B->A"), ("ticker_blocked", "A->B"), ("ticker_blocked", "B->A")):
                x = g[(g["variant"] == variant) & (g["direction"] == direction)].iloc[0]
                cells.append(f"{f(x.min_corr)} / {f(x.med_corr)}; ARI {f(x.ari)} (n {n(x.n_other)})")
            w(f"| {method} | {k} | " + " | ".join(cells) + " |")
        w("")
        co = pd.read_parquet(S.art(f"t3_{v}_coassign.parquet"))
        cq = co.groupby(["method", "k"])["co_assignment_rate"].quantile([.25, .5, .75]).unstack()
        w("Co-assignment rate over 50 ticker bootstraps, median (p25, p75): " +
          "; ".join(f"{m} k={k} {f(r[0.5])} ({f(r[0.25])}, {f(r[0.75])})" for (m, k), r in cq.iterrows()) + ".")
        w("")
        lab = pd.read_parquet(S.art(f"t3_{v}_structure.parquet"))
        lc = lab.groupby(["method", "k"])["structure_label"].value_counts().unstack(fill_value=0)
        w("Structure labels per cluster (beats the null at its k, and its own fit on each period reproduces it at correlation ≥ 0.9; "
          "S1's operational cuts, declared in config before the run):")
        w("")
        w("| method | k | " + " | ".join(lc.columns) + " |")
        w("|---|---|" + "---|" * len(lc.columns))
        for (m, k), r in lc.iterrows():
            w(f"| {m} | {k} | " + " | ".join(n(r[c]) for c in lc.columns) + " |")
        w("")
        if v == "post":
            xt = pd.read_parquet(S.art("t3_post_theory_x_cluster.parquet"))
            w("Theory types × clusters (section 4d), post view — each cluster's size and its two largest theory types:")
            w("")
            for (m, k), g in xt.groupby(["method", "k"]):
                parts = []
                for lbl, h in g.groupby("label"):
                    tot = h["n"].sum()
                    top = h.sort_values("n", ascending=False).head(2)
                    parts.append(f"{lbl}: n {n(tot)} — " + ", ".join(f"{r.theory_type} {pct(r.n / tot, 0)}" for r in top.itertuples()))
                w(f"- {m} k={k}: " + "; ".join(parts))
            w("")
    w("→ `charts/null_comparison.html`, `charts/stability.html`, `charts/atlas.html`")
    w("")
    # ------------------------------------------------ 5. run-up
    w("## 4. Run-up shapes and the transition table (section 5)")
    w("")
    w("Declared classes (first match wins): gap (`gap_share` ≥ 0.8), late spike (`u_launch` ≥ 0.8), grind; an event whose run-up is "
      "unavailable and is not a gap is its own class, named by the reason. Counts: " +
      "; ".join(f"{k} {n(v)}" for k, v in t4["runup_classes"].items()) + ".")
    w("")
    rd = pd.read_parquet(S.art("t4_runup_descriptors.parquet"))
    w("| class | " + " | ".join(["gap_share", "runup_u_launch", "runup_height_s", "runup_max_drawdown_s", "runup_pushes", "runup_minutes"]) + " |")
    w("|---|---|---|---|---|---|---|")
    for cl, g in rd.groupby("runup_class"):
        gi = g.set_index("descriptor")
        cells = [f"{f(gi.loc[d, 'q0500'], 2)} ({f(gi.loc[d, 'q0250'], 2)}, {f(gi.loc[d, 'q0750'], 2)}; n {n(gi.loc[d, 'n'])})" if gi.loc[d, "n"] else "—"
                 for d in ["gap_share", "runup_u_launch", "runup_height_s", "runup_max_drawdown_s", "runup_pushes", "runup_minutes"]]
        w(f"| {cl} | " + " | ".join(cells) + " |")
    w("")
    tr = pd.read_parquet(S.art("t4_transitions.parquet"))
    for seg in ["all"] + sorted(x for x in tr["segment"].unique() if x != "all"):
        m = tr[(tr["runup_typing"] == "declared") & (tr["post_typing"] == "theory") & (tr["segment"] == seg)]
        if m.empty:
            continue
        piv = m.pivot(index="runup_type", columns="post_type", values="row_share").fillna(0)
        cnt = m.pivot(index="runup_type", columns="post_type", values="n").fillna(0).astype(int)
        cols = [c for c in S.TYPES if c in piv.columns] + [c for c in piv.columns if c not in S.TYPES]
        w(f"Run-up class → theory type (N = 100), segment **{seg}** — row share (n):")
        w("")
        w("| run-up class (row n) | " + " | ".join(cols) + " |")
        w("|---|" + "---|" * len(cols))
        rown = m.drop_duplicates("runup_type").set_index("runup_type")["row_n"]
        for r in piv.index:
            w(f"| {r} ({n(rown[r])}) | " + " | ".join(f"{pct(piv.loc[r, c], 0)} ({n(cnt.loc[r, c])})" for c in cols) + " |")
        w("")
    w("→ `charts/transitions.html` (selector: declared classes and run-up clusters → theory types and post clusters, every k, every segment)")
    w("")
    # ------------------------------------------------ 6. atlas
    d = pd.read_parquet(S.art("t5_descriptors.parquet"))
    tt = pd.read_parquet(S.art("s1_theory_types.parquet"))
    tt = tt[tt["N"] == 100].set_index("event_id")
    d["theory_type"] = tt.loc[d["event_id"], "theory_type"].to_numpy()
    w("## 5. The atlas (section 6)")
    w("")
    w(f"{n(t5['atlas_entries'])} atlas entries (every theory type, every declared run-up class, every cluster of both methods at every k "
      "in every view), each with centroid, IQR band, null centroid, a 24-path gallery, money and every descriptor's distribution — "
      "in `charts/atlas.html`. Theory types at N = 100, median (p25, p75; n):")
    w("")
    rows = [("post100_rise_bp", "rise_bp"), ("excess_rise_bp", "excess rise, bp"), ("rise_cents", "rise_cents"), ("post100_fall_bp", "fall_bp"),
            ("minutes_to_peak", "minutes τ → peak"), ("turnover", "turnover"), ("trades_per_min_finest", "trades/min, finest valid rung"),
            ("dollars_per_min_finest", "$/min, finest valid rung"), ("flow_share_rest_finest", "flow_share (rest of session)"),
            ("live_n_rest", "live_n (rest of session)"), ("competition_excess_j", "competition excess as the crosser"),
            ("shs_shares_outstanding_corrected", "shares outstanding (D39)"), ("short_interest_share", "short interest / shares (D39)"),
            ("jump_share", "jump_share"), ("hours_after_0400", "hours after 04:00"), ("gap_share", "gap_share"), ("runup_u_launch", "u_launch")]
    types = [t for t in S.TYPES if t in set(d["theory_type"].dropna())]
    w("| quantity | " + " | ".join(types) + " |")
    w("|---|" + "---|" * len(types))
    for col, lab in rows:
        w(f"| {lab} | " + " | ".join(iqr(d[d["theory_type"] == t][col]) for t in types) + " |")
    for col, lab in (("a2_ignition", "a2_ignition TRUE"), ("filing_24h", "filing within 24 h"), ("flg_dilution_form_before_t0", "dilution flag (D39)"),
                     ("spl_reverse_split_365d", "reverse split in 365 d (D39)"), ("halt_in_path", "halt in path"),
                     ("flag_cross_session_extreme", "A12 flag")):
        cells = []
        for t in types:
            v = d[d["theory_type"] == t][col]
            k = v.notna().sum()
            cells.append(f"{pct(v.fillna(False).astype(bool).sum() / max(1, k))} (n {n(k)})")
        w(f"| {lab} | " + " | ".join(cells) + " |")
    w("")
    tb = pd.read_parquet(S.art("t5_type_by_date.parquet"))
    w("**Type share by date** — chi-square of the date × type table against 200 seeded permutations of the type labels across events "
      "(dates and per-date counts fixed):")
    w("")
    w("| view | typing | k | events | dates | observed | permutation mean · p95 | observed / mean | permutations ≥ observed |")
    w("|---|---|---|---|---|---|---|---|---|")
    for r in tb.itertuples():
        w(f"| {r.view} | {r.typing} | {'' if r.k != r.k or r.k is None else int(r.k)} | {n(r.events)} | {n(r.dates)} | {f(r.chi2_observed, 0)} | "
          f"{f(r.chi2_perm_mean, 0)} · {f(r.chi2_perm_p95, 0)} | {f(r.ratio_obs_to_perm_mean, 2)} | {pct(r.share_perm_ge_observed)} |")
    w("")
    w("## 6. Charts (under `results/shape_atlas/s1/charts/`, dark theme, Plotly inlined)")
    w("")
    for p in sorted((S.REPO / S.CHARTS).glob("*.html")):
        w(f"- `{p.name}`")
    w("")
    txt = "\n".join(L) + "\n"
    out = S.REPO / S.OUT / "REPORT.md"
    out.write_text(txt, encoding="utf-8", newline="\n")
    shutil.copyfile(out, S.REPO / "results" / "reports" / "shape_atlas_s1_report.md")
    print(f"REPORT.md written ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
